// GET /api/orders/packing-slip/:id — Packing slip PDF for a sale.
// :id = sale id. Load sale (scoped by bucket_id) + its sale_lines ordered by
// position, optional shipment row for carrier/tracking, and base_currency.
// Rows show product x qty x formatted money. Footer shows order total.
// All queries are scoped by clientId so a cross-tenant id reads as 404.
import { jsonError } from './_shared/http';
import { db } from './_shared/db';
import { requireOrders } from './_orders-authz';
import { renderPdf } from './_shared/pdf';
import { formatMoney } from '../../src/lib/currency';

export const config = { path: '/api/orders/packing-slip/:id', method: 'GET' };

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function idFrom(req: Request): string { return new URL(req.url).pathname.split('/').pop() ?? ''; }

export default async function handler(req: Request): Promise<Response> {
  const id = idFrom(req);
  if (!UUID_RE.test(id)) return jsonError(404, 'not_found');

  const a = await requireOrders(req, ['orders.business.view']);
  if (!a.ok) return a.res;
  const { clientId } = a.ctx;

  const sql = db();

  const sales = (await sql`
    SELECT s.id, s.order_no, s.status, s.channel, s.customer_name,
           to_char(s.created_at, 'YYYY-MM-DD') AS created_date,
           s.total_cents,
           c.base_currency
    FROM public.sales s
    JOIN public.clients c ON c.id = s.bucket_id
    WHERE s.id = ${id}::uuid AND s.bucket_id = ${clientId}::uuid
    LIMIT 1
  `) as Array<{
    id: string;
    order_no: number;
    status: string;
    channel: string;
    customer_name: string | null;
    created_date: string;
    total_cents: string;
    base_currency: string;
  }>;

  if (!sales[0]) return jsonError(404, 'not_found');
  const sale = sales[0];
  const baseCurrency = sale.base_currency;

  const lines = (await sql`
    SELECT product_name_snap, qty, line_total_cents
    FROM public.sale_lines
    WHERE sale_id = ${id}::uuid
    ORDER BY position ASC
  `) as Array<{ product_name_snap: string; qty: number; line_total_cents: string }>;

  // Optional shipment row — carrier and tracking if one exists.
  const shipments = (await sql`
    SELECT carrier, tracking_ref
    FROM public.orders_shipments
    WHERE sale_id = ${id}::uuid AND client_id = ${clientId}::uuid
    ORDER BY created_at DESC
    LIMIT 1
  `) as Array<{ carrier: string | null; tracking_ref: string | null }>;

  const shipment = shipments[0] ?? null;

  const meta: Array<{ label: string; value: string }> = [
    { label: 'Customer', value: sale.customer_name ?? 'Guest' },
    { label: 'Channel', value: sale.channel },
    { label: 'Date', value: sale.created_date },
  ];
  if (shipment?.carrier) {
    meta.push({ label: 'Carrier', value: shipment.carrier });
  }
  if (shipment?.tracking_ref) {
    meta.push({ label: 'Tracking', value: shipment.tracking_ref });
  }

  const totalFormatted = formatMoney(Number(sale.total_cents), baseCurrency);

  const doc = {
    title: `Packing Slip #${sale.order_no}`,
    heading: `Packing Slip - Order #${sale.order_no}`,
    meta,
    rows: lines.map((l) => ({
      label: `${l.product_name_snap} x${l.qty}`,
      value: formatMoney(Number(l.line_total_cents), baseCurrency),
    })),
    footer: `Total: ${totalFormatted} | Generated by ExSol Orders`,
  };

  const bytes = await renderPdf(doc);
  // pdf-lib returns Uint8Array<ArrayBufferLike> whose buffer may be SharedArrayBuffer
  // in TypeScript's view; cast via unknown so the BodyInit check passes. At runtime
  // Netlify Functions v2 / Node 18+ accepts Uint8Array directly in the Response body.
  return new Response(bytes as unknown as BodyInit, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="packing-slip-${sale.order_no}.pdf"`,
    },
  });
}
