// GET /api/orders/pick-list/:id — Pick list PDF for a sale.
// :id = sale id. Load sale (scoped by bucket_id) + its sale_lines ordered by
// position, build a PdfDoc, and return PDF bytes.
// All queries are scoped by clientId so a cross-tenant id reads as 404.
import { jsonError } from './_shared/http';
import { db } from './_shared/db';
import { requireOrders } from './_orders-authz';
import { renderPdf } from './_shared/pdf';

export const config = { path: '/api/orders/pick-list/:id', method: 'GET' };

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
function idFrom(req: Request): string { return new URL(req.url).pathname.split('/').pop() ?? ''; }

export default async function handler(req: Request): Promise<Response> {
  const id = idFrom(req);
  if (!UUID_RE.test(id)) return jsonError(404, 'not_found');

  const a = await requireOrders(req, ['orders.business.view']);
  if (!a.ok) return a.res;
  const { clientId } = a.ctx;

  const sql = db();

  const sales = (await sql`
    SELECT id, order_no, status, channel, customer_name,
           to_char(created_at, 'YYYY-MM-DD') AS created_date
    FROM public.sales
    WHERE id = ${id}::uuid AND bucket_id = ${clientId}::uuid
    LIMIT 1
  `) as Array<{
    id: string;
    order_no: number;
    status: string;
    channel: string;
    customer_name: string | null;
    created_date: string;
  }>;

  if (!sales[0]) return jsonError(404, 'not_found');
  const sale = sales[0];

  const lines = (await sql`
    SELECT product_name_snap, qty
    FROM public.sale_lines
    WHERE sale_id = ${id}::uuid
    ORDER BY position ASC
  `) as Array<{ product_name_snap: string; qty: number }>;

  const doc = {
    title: `Pick List #${sale.order_no}`,
    heading: `Pick List - Order #${sale.order_no}`,
    meta: [
      { label: 'Customer', value: sale.customer_name ?? 'Guest' },
      { label: 'Channel', value: sale.channel },
      { label: 'Date', value: sale.created_date },
    ],
    rows: lines.map((l) => ({ label: `${l.product_name_snap} x${l.qty}`, value: '[ ] picked' })),
    footer: 'Generated by ExSol Orders',
  };

  const bytes = await renderPdf(doc);
  // pdf-lib returns Uint8Array<ArrayBufferLike> whose buffer may be SharedArrayBuffer
  // in TypeScript's view; cast via unknown so the BodyInit check passes. At runtime
  // Netlify Functions v2 / Node 18+ accepts Uint8Array directly in the Response body.
  return new Response(bytes as unknown as BodyInit, {
    status: 200,
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="pick-list-${sale.order_no}.pdf"`,
    },
  });
}
