import { useEffect, useState } from 'react';
import { Button } from '../../../../components/ui/Button';
import { EmptyState, ErrorState, LoadingState } from '../../../../components/ui/Feedback';
import { Field, Input } from '../../../../components/ui/Field';
import { StatusBadge } from '../../../../components/ui/StatusBadge';
import { TableFrame } from '../../../../components/ui/Table';
import { OrdersApiError, ordersApi } from '../../shared/api';
import type { PickupRow } from '../../shared/types';

export default function PickupsTab({ perms }: { perms: ReadonlySet<string> }) {
  const [rows, setRows] = useState<PickupRow[]>([]); const [saleId, setSaleId] = useState(''); const [selected, setSelected] = useState<PickupRow | null>(null); const [name, setName] = useState(''); const [last4, setLast4] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const canCreate = perms.has('orders.business.create'); const canEdit = perms.has('orders.business.edit');
  const load = () => { setLoading(true); ordersApi.listPickups().then((next) => { setRows(next); setError(null); }).catch((e) => setError(e instanceof OrdersApiError ? e.code : 'network_error')).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  async function ready(event: React.FormEvent) { event.preventDefault(); if (!saleId.trim()) return; setSaving(true); try { await ordersApi.markPickupReady(saleId.trim()); setSaleId(''); load(); } catch (e) { setError(e instanceof OrdersApiError ? e.code : 'network_error'); } finally { setSaving(false); } }
  async function collect(event: React.FormEvent) { event.preventDefault(); if (!selected || !name.trim() || !/^\d{4}$/.test(last4)) return; setSaving(true); try { await ordersApi.collectPickup(selected.id, name.trim(), last4); setSelected(null); setName(''); setLast4(''); load(); } catch (e) { setError(e instanceof OrdersApiError ? e.code : 'network_error'); } finally { setSaving(false); } }
  return <section className="ord-pickups"><div className="ord-queue__heading"><div><h2 className="ord-section-title">Pickup handoff</h2><p className="ord-muted">Ready proof is separate from stock completion. Store only the collector name and last four digits.</p></div><Button variant="secondary" onClick={load} loading={loading}>Refresh</Button></div>{canCreate && <form className="ord-form-row" onSubmit={ready}><Field label="Pickup sale ID">{(props) => <Input {...props} value={saleId} onChange={(e) => setSaleId(e.target.value)} placeholder="Sale UUID" />}</Field><Button type="submit" loading={saving}>Mark ready</Button></form>}{loading ? <LoadingState title="Loading pickups" /> : error ? <ErrorState title="Pickup handoff could not load" action={<Button variant="secondary" onClick={load}>Try again</Button>}>{error}</ErrorState> : rows.length === 0 ? <EmptyState title="No pickup handoffs yet." /> : <TableFrame caption="Pickup handoffs" density="compact"><thead><tr><th>Order</th><th>Customer</th><th>Status</th><th>Ready</th><th>Collected</th>{canEdit && <th>Action</th>}</tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td>#{row.order_no}</td><td>{row.customer_name}</td><td><StatusBadge icon="•" label={row.status === 'ready' ? 'Ready for pickup' : 'Collected'} tone={row.status === 'collected' ? 'success' : 'info'} /></td><td>{new Date(row.ready_at).toLocaleString()}</td><td>{row.collected_at ? `${row.collector_name} · •••• ${row.collector_phone_last4}` : '—'}</td>{canEdit && <td>{row.status === 'ready' && <Button size="compact" onClick={() => setSelected(row)}>Record collection</Button>}</td>}</tr>)}</tbody></TableFrame>}{selected && <form className="ord-pickups__collect" onSubmit={collect}><h3>Record collection for #{selected.order_no}</h3><Field label="Collector name">{(props) => <Input {...props} value={name} onChange={(e) => setName(e.target.value)} />}</Field><Field label="Phone last four digits">{(props) => <Input {...props} inputMode="numeric" maxLength={4} value={last4} onChange={(e) => setLast4(e.target.value.replace(/\D/g, ''))} />}</Field><div className="ord-actions"><Button type="submit" loading={saving}>Confirm collected</Button><Button type="button" variant="quiet" onClick={() => setSelected(null)}>Cancel</Button></div></form>}</section>;
}
