import { describe, it, expect } from 'vitest';
import { PDFDocument } from 'pdf-lib';
import { renderPdf } from '../../netlify/functions/_shared/pdf';

describe('renderPdf', () => {
  it('produces a valid, loadable PDF', async () => {
    const bytes = await renderPdf({
      title: 'Invoice INV-1042',
      heading: "Papa's Salon",
      meta: [{ label: 'Invoice #', value: 'INV-1042' }, { label: 'Date', value: '2026-07-06' }],
      bodyLines: ['Thank you for your business.'],
      rows: [{ label: 'Total', value: 'Rs 620.00' }],
      footer: 'Generated by ExSol',
    });
    expect(bytes.length).toBeGreaterThan(100);
    expect(new TextDecoder().decode(bytes.slice(0, 5))).toBe('%PDF-');
    const loaded = await PDFDocument.load(bytes);
    expect(loaded.getPageCount()).toBe(1);
  });

  it('does not throw on non-WinAnsi characters (₹, smart quotes)', async () => {
    const bytes = await renderPdf({
      heading: 'Receipt',
      rows: [{ label: 'Total', value: '₹620.00' }],
      bodyLines: ['“Thanks” — see you soon…'],
    });
    expect(new TextDecoder().decode(bytes.slice(0, 5))).toBe('%PDF-');
  });

  it('paginates when content overflows a page', async () => {
    const many = Array.from({ length: 120 }, (_, i) => `Line item ${i + 1}`);
    const bytes = await renderPdf({ heading: 'Long report', bodyLines: many });
    const loaded = await PDFDocument.load(bytes);
    expect(loaded.getPageCount()).toBeGreaterThan(1);
  });
});
